export default function useUndefinedProps(props) {
  const {
    display,
    breakpoints,
    width,
    minWidth,
    maxWidth,
    height,
    minHeight,
    maxHeight,
    colspan,
    cols,
    margin,
    marginLeft,
    marginRight,
    marginTop,
    marginBottom,
    padding,
    paddingLeft,
    paddingRight,
    paddingTop,
    paddingBottom,
    gridRowGap,
    gridColumnGap,
    gridTemplateRows,
    gridAutoRows,
    gridTemplateColumns,
    autoFlow,
    component,
    innerHTML,

    pointerEvents,

    onResize,
    onIntersect,
    root,
    rootMargin,
    threshold,

    styles,
    as,
    control,
    controlColor,
    order,
    position,
    zIndex,
    top,
    bottom,
    left,
    right,
    alignItems,
    alignContent,
    alignSelf,
    justifyContent,
    justifyItems,
    justifySelf,
    flexDirection,
    flexWrap,
    flexShrink,
    flexGrow,
    background,
    backgroundColor,
    backgroundImage,
    backgroundPosition,
    backgroundSize,
    backgroundAttachment,

    filter,
    backdropFilter,
    mixBlendMode,
    backgroundBlendMode,
    textShadow,
    boxShadow,
    textStroke,

    border,
    borderLeft,
    borderRight,
    borderTop,
    borderBottom,
    fontFamily,
    fontSize,
    color,
    lineHeight,
    letterSpacing,
    textDecoration,
    hyphens,

    overflow,
    overflowX,
    overflowY,

    transition,
    animation,
    opacity,
    transform,
    className,
    children,
    isControl,
    ref,
    ...rest
  } = props;
  return rest;
}
